language: node_js
services: mysql
node_js:
  - 0.8
  - 0.10
before_script:
  - mysql -e 'create database test_mysql_stream_db;'
notifications:
  email:
    recipients:
      - brianloveswords@gmail.com